security:
    encoders:
        App\Entity\User:
            algorithm: auto
    providers:
        db_provider:
            entity:
                class: App\Entity\User
                property: username
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            provider:  db_provider
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path:   /logout
                target: /
    role_hierarchy:
      ROLE_ADMIN: ROLE_USER